spring.application.name=spring_ai_rag

ollama.base-url=http://localhost:11434
ollama.model=tinyllama

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.url=jdbc:postgresql://localhost:5432/assistant
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
